# Generated by Django 3.2.7 on 2021-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminthanima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_pic1', models.CharField(max_length=60)),
                ('event_name1', models.CharField(max_length=40)),
                ('event_discription1', models.CharField(max_length=255)),
                ('event_pic2', models.CharField(max_length=60)),
                ('event_name2', models.CharField(max_length=40)),
                ('event_discription2', models.CharField(max_length=255)),
                ('event_pic3', models.CharField(max_length=60)),
                ('event_name3', models.CharField(max_length=40)),
                ('event_discription3', models.CharField(max_length=255)),
                ('event_pic4', models.CharField(max_length=60)),
                ('event_name4', models.CharField(max_length=40)),
                ('event_discription4', models.CharField(max_length=255)),
                ('event_pic5', models.CharField(max_length=60)),
                ('event_name5', models.CharField(max_length=40)),
                ('event_discription5', models.CharField(max_length=255)),
                ('event_pic6', models.CharField(max_length=60)),
                ('event_name6', models.CharField(max_length=40)),
                ('event_discription6', models.CharField(max_length=255)),
            ],
        ),
    ]
