# Generated by Django 3.2.7 on 2021-11-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanima', '0002_userbookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookings',
        ),
    ]
