# Generated by Django 3.2.7 on 2021-11-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelDetails',
        ),
    ]
