# Generated by Django 3.2.7 on 2021-11-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0002_delete_hoteldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('hotel_name', models.CharField(max_length=40)),
                ('hotel_description', models.CharField(max_length=256)),
                ('price_single', models.IntegerField()),
                ('price_double', models.IntegerField()),
                ('age', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('district', models.CharField(max_length=40)),
                ('ower_profile', models.CharField(max_length=100)),
                ('hotel_picture1', models.CharField(max_length=100)),
                ('hotel_picture2', models.CharField(max_length=100)),
                ('hotel_picture3', models.CharField(max_length=100)),
            ],
        ),
    ]
