# Generated by Django 3.2.7 on 2021-12-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hoteldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotalAvalibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('today_date', models.DateField()),
                ('avl_single_room', models.IntegerField()),
                ('avl_double_room', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
