# Generated by Django 3.2.7 on 2021-12-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotalavalibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotalAvalibility',
        ),
    ]
