# Generated by Django 3.2.7 on 2022-01-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20220117_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookings',
            name='booking_user_mobile',
        ),
    ]
