# Generated by Django 3.2.7 on 2022-01-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_userbookings_booking_user_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookings',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
